[package]
name = "tempest"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"

[dev-dependencies]
clap = {version="*", features=["derive", "wrap_help"]}
